In [1]:
import numpy as np

my_arr = np.arange(1000000)

In [2]:
my_list = list(range(1000000))

In [3]:
%time for _ in range(10): my_arr2 = my_arr*2

CPU times: user 15.4 ms, sys: 8.64 ms, total: 24 ms
Wall time: 23.4 ms


In [4]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: user 497 ms, sys: 110 ms, total: 607 ms
Wall time: 605 ms


In [5]:
data = np.random.randn(2, 3)

In [6]:
data

array([[-1.29136083, -0.8659316 ,  0.80850631],
       [-0.78034163,  0.32798945, -0.70933227]])

In [7]:
data * 10

array([[-12.91360827,  -8.65931603,   8.08506312],
       [ -7.80341629,   3.27989446,  -7.09332268]])

In [8]:
data + data

array([[-2.58272165, -1.73186321,  1.61701262],
       [-1.56068326,  0.65597889, -1.41866454]])

In [9]:
data.shape

(2, 3)

In [10]:
data.dtype

dtype('float64')

In [11]:
data1 = [6, 7.5, 8, 0, 1]

In [12]:
arr1 = np.array(data1)

In [13]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [14]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

In [15]:
arr2 = np.array(data2)

In [16]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [17]:
 arr2.ndim

2

In [18]:
arr2.shape

(2, 4)

In [19]:
arr1.dtype

dtype('float64')

In [20]:
arr2.dtype

dtype('int64')

In [21]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [23]:
np.empty(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [25]:
np.empty(1)

array([1.])

In [27]:
t = np.arange(15)

In [28]:
t.dtype

dtype('int64')

In [29]:
np.full(1, 10)

array([10])

In [30]:
np.full(10, 23)

array([23, 23, 23, 23, 23, 23, 23, 23, 23, 23])

In [31]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [32]:
arr1 = np.array([1, 2, 3], dtype=np.float32)

In [33]:
arr2 = np.array([1, 2, 3], dtype=np.int32)

In [34]:
arr1.dtype

dtype('float32')

In [35]:
arr1 + arr2

array([2., 4., 6.])

In [36]:
arr2.astype(np.float128)

array([1., 2., 3.], dtype=float128)

In [37]:
arr1.astype(np.int32)

array([1, 2, 3], dtype=int32)

In [38]:
nu_string = np.array(['-1.23', '11.2323', '1'])

In [39]:
nu_string

array(['-1.23', '11.2323', '1'], dtype='<U7')

In [40]:
nu_string.astype(np.float128)

array([-1.23  , 11.2323,  1.    ], dtype=float128)

In [41]:
nnn_ = np.array(['adfaf',' 123'])

In [42]:
nnn_

array(['adfaf', ' 123'], dtype='<U5')

In [43]:
nnn_.astype(np.int32)

ValueError: invalid literal for int() with base 10: 'adfaf'

In [44]:
np.arange(10).astype(np.float)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [47]:
arr1 * arr1

array([1., 4., 9.], dtype=float32)

In [48]:
arr2

array([1, 2, 3], dtype=int32)

In [49]:
arr1 == arr2

array([ True,  True,  True])

In [50]:
arr1 + arr2

array([2., 4., 6.])

In [52]:
arr = np.arange(100)

In [53]:
arr[10]

10

In [54]:
arr[5:9]

array([5, 6, 7, 8])

In [55]:
arr[0]

0

In [56]:
arr[-1]

99

In [60]:
arr_slice = arr [1:10]

In [61]:
arr_slice[1] = 100

In [62]:
arr[1:14]

array([  1, 100,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13])

In [63]:
arr2 = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [64]:
arr2[2]

array([7, 8, 9])

In [65]:
arr2[1][1]

5

In [66]:
arr2[1, 1]

5

In [67]:
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [68]:
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [69]:
arr3[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [70]:
arr[2]

100

In [71]:
arr3[2]

IndexError: index 2 is out of bounds for axis 0 with size 2

In [72]:
arr3[1]

array([[ 7,  8,  9],
       [10, 11, 12]])

In [73]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [74]:
arr2[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [75]:
arr2[:1]

array([[1, 2, 3]])

In [76]:
arr2[:2, 1:]

array([[2, 3],
       [5, 6]])

In [79]:
arr2[1, :2]

array([4, 5])

In [78]:
arr2[:2, 2]

array([3, 6])

In [80]:
arr2[:, :1]

array([[1],
       [4],
       [7]])

In [81]:
arr2[2:, :]

array([[7, 8, 9]])

In [82]:
arr2[2]

array([7, 8, 9])

In [84]:
arr2[2, :]

array([7, 8, 9])

In [85]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])