In [3]:
import numpy as np

my_arr = np.arange(1000000)

In [4]:
my_list = list(range(1000000))

In [5]:
%time for _ in range(10): my_arr2 = my_arr*2

CPU times: user 13.7 ms, sys: 4.3 ms, total: 18 ms
Wall time: 17.5 ms


In [6]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: user 481 ms, sys: 117 ms, total: 598 ms
Wall time: 597 ms


In [7]:
data = np.random.randn(2, 3)

In [8]:
data

array([[-1.16263076, -1.31029456, -0.69011706],
       [ 0.27305281, -1.28957984, -0.4271038 ]])

In [9]:
data * 10

array([[-11.62630756, -13.10294558,  -6.90117061],
       [  2.73052808, -12.89579838,  -4.27103797]])

In [10]:
data + data

array([[-2.32526151, -2.62058912, -1.38023412],
       [ 0.54610562, -2.57915968, -0.85420759]])

In [11]:
data.shape

(2, 3)

In [12]:
data.dtype

dtype('float64')

In [13]:
data1 = [6, 7.5, 8, 0, 1]

In [14]:
arr1 = np.array(data1)

In [15]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [16]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

In [17]:
arr2 = np.array(data2)

In [18]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [19]:
 arr2.ndim

2

In [20]:
arr2.shape

(2, 4)

In [21]:
arr1.dtype

dtype('float64')

In [22]:
arr2.dtype

dtype('int64')

In [23]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [24]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [25]:
np.empty(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [26]:
np.empty(1)

array([1.])

In [27]:
t = np.arange(15)

In [28]:
t.dtype

dtype('int64')

In [29]:
np.full(1, 10)

array([10])

In [30]:
np.full(10, 23)

array([23, 23, 23, 23, 23, 23, 23, 23, 23, 23])

In [31]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [32]:
arr1 = np.array([1, 2, 3], dtype=np.float32)

In [33]:
arr2 = np.array([1, 2, 3], dtype=np.int32)

In [34]:
arr1.dtype

dtype('float32')

In [35]:
arr1 + arr2

array([2., 4., 6.])

In [36]:
arr2.astype(np.float128)

array([1., 2., 3.], dtype=float128)

In [37]:
arr1.astype(np.int32)

array([1, 2, 3], dtype=int32)

In [38]:
nu_string = np.array(['-1.23', '11.2323', '1'])

In [39]:
nu_string

array(['-1.23', '11.2323', '1'], dtype='<U7')

In [40]:
nu_string.astype(np.float128)

array([-1.23  , 11.2323,  1.    ], dtype=float128)

In [41]:
nnn_ = np.array(['adfaf',' 123'])

In [42]:
nnn_

array(['adfaf', ' 123'], dtype='<U5')

In [43]:
nnn_.astype(np.int32)

ValueError: invalid literal for int() with base 10: 'adfaf'

In [44]:
np.arange(10).astype(np.float)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [45]:
arr1 * arr1

array([1., 4., 9.], dtype=float32)

In [46]:
arr2

array([1, 2, 3], dtype=int32)

In [47]:
arr1 == arr2

array([ True,  True,  True])

In [48]:
arr1 + arr2

array([2., 4., 6.])

In [49]:
arr = np.arange(100)

In [50]:
arr[10]

10

In [51]:
arr[5:9]

array([5, 6, 7, 8])

In [52]:
arr[0]

0

In [53]:
arr[-1]

99

In [54]:
arr_slice = arr [1:10]

In [55]:
arr_slice[1] = 100

In [56]:
arr[1:14]

array([  1, 100,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13])

In [57]:
arr2 = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [58]:
arr2[2]

array([7, 8, 9])

In [59]:
arr2[1][1]

5

In [60]:
arr2[1, 1]

5

In [61]:
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [62]:
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [63]:
arr3[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [64]:
arr[2]

100

In [65]:
arr3[2]

IndexError: index 2 is out of bounds for axis 0 with size 2

In [66]:
arr3[1]

array([[ 7,  8,  9],
       [10, 11, 12]])

In [67]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [68]:
arr2[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [69]:
arr2[:1]

array([[1, 2, 3]])

In [70]:
arr2[:2, 1:]

array([[2, 3],
       [5, 6]])

In [71]:
arr2[1, :2]

array([4, 5])

In [72]:
arr2[:2, 2]

array([3, 6])

In [73]:
arr2[:, :1]

array([[1],
       [4],
       [7]])

In [74]:
arr2[2:, :]

array([[7, 8, 9]])

In [75]:
arr2[2]

array([7, 8, 9])

In [76]:
arr2[2, :]

array([7, 8, 9])

In [77]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [78]:
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [79]:
old = arr3[0].copy()

In [80]:
arr3[0] = 101

In [81]:
arr3

array([[[101, 101, 101],
        [101, 101, 101]],

       [[  7,   8,   9],
        [ 10,  11,  12]]])

In [82]:
arr3[0] = old

In [83]:
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [84]:
arr3[1, 0]

array([7, 8, 9])

In [85]:
arr3[1, 1]

array([10, 11, 12])

In [86]:
arr3.shape

(2, 2, 3)

In [87]:
arr3[0,0,0]

1

In [88]:
arr1

array([1., 2., 3.], dtype=float32)

In [89]:
arr1 = np.arange(20)

In [90]:
arr1[1:6]

array([1, 2, 3, 4, 5])

In [91]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [92]:
arr2[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [93]:
arr2[2]

array([7, 8, 9])

In [94]:
arr2[:2, 1:]

array([[2, 3],
       [5, 6]])

In [95]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [96]:
arr2[1, :2]

array([4, 5])

In [97]:
arr2[:2, 2]

array([3, 6])

In [98]:
arr2[:, :1]

array([[1],
       [4],
       [7]])

In [99]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [100]:
arr2[:, 1]

array([2, 5, 8])

In [101]:
arr2[:, 1:2]

array([[2],
       [5],
       [8]])

In [102]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [103]:
data = np.random.randn(7, 4)

In [104]:
data

array([[ 1.33452146, -0.71888134, -3.16556842,  1.41518756],
       [-2.07614586,  1.53416142, -0.37021066, -0.156386  ],
       [ 0.25862925,  0.24653787, -0.18666713,  1.23972057],
       [ 0.50098281,  2.30627981, -0.47770822, -1.21238371],
       [-0.68956212,  0.02203024, -0.97118628, -1.29340985],
       [-0.20151362,  0.12389771,  1.1599146 ,  1.30603976],
       [-0.96003455, -0.90992736, -0.10247287,  0.15139536]])

In [105]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [106]:
names[names=='Bob']

array(['Bob', 'Bob'], dtype='<U4')

In [107]:
names=='Bob'

array([ True, False, False,  True, False, False, False])

In [108]:
data[1]

array([-2.07614586,  1.53416142, -0.37021066, -0.156386  ])

In [109]:
data[names=='Bob']

array([[ 1.33452146, -0.71888134, -3.16556842,  1.41518756],
       [ 0.50098281,  2.30627981, -0.47770822, -1.21238371]])

In [110]:
data[[0,3]]

array([[ 1.33452146, -0.71888134, -3.16556842,  1.41518756],
       [ 0.50098281,  2.30627981, -0.47770822, -1.21238371]])

In [111]:
data[[0, 3], 2:]

array([[-3.16556842,  1.41518756],
       [-0.47770822, -1.21238371]])

In [112]:
data[names=='Bob', 2:]

array([[-3.16556842,  1.41518756],
       [-0.47770822, -1.21238371]])

In [113]:
data[names=='Bob', 3]

array([ 1.41518756, -1.21238371])

In [114]:
cond = names == 'Bob'

In [115]:
data[~cond]

array([[-2.07614586,  1.53416142, -0.37021066, -0.156386  ],
       [ 0.25862925,  0.24653787, -0.18666713,  1.23972057],
       [-0.68956212,  0.02203024, -0.97118628, -1.29340985],
       [-0.20151362,  0.12389771,  1.1599146 ,  1.30603976],
       [-0.96003455, -0.90992736, -0.10247287,  0.15139536]])

In [116]:
data[names!='Bob']

array([[-2.07614586,  1.53416142, -0.37021066, -0.156386  ],
       [ 0.25862925,  0.24653787, -0.18666713,  1.23972057],
       [-0.68956212,  0.02203024, -0.97118628, -1.29340985],
       [-0.20151362,  0.12389771,  1.1599146 ,  1.30603976],
       [-0.96003455, -0.90992736, -0.10247287,  0.15139536]])

In [117]:
mask = (names=='Bob') | (names=='Will')

In [118]:
data[mask]

array([[ 1.33452146, -0.71888134, -3.16556842,  1.41518756],
       [ 0.25862925,  0.24653787, -0.18666713,  1.23972057],
       [ 0.50098281,  2.30627981, -0.47770822, -1.21238371],
       [-0.68956212,  0.02203024, -0.97118628, -1.29340985]])

In [119]:
data[~mask]

array([[-2.07614586,  1.53416142, -0.37021066, -0.156386  ],
       [-0.20151362,  0.12389771,  1.1599146 ,  1.30603976],
       [-0.96003455, -0.90992736, -0.10247287,  0.15139536]])

In [120]:
n = data[mask]
n

array([[ 1.33452146, -0.71888134, -3.16556842,  1.41518756],
       [ 0.25862925,  0.24653787, -0.18666713,  1.23972057],
       [ 0.50098281,  2.30627981, -0.47770822, -1.21238371],
       [-0.68956212,  0.02203024, -0.97118628, -1.29340985]])

In [121]:
n[:] = 0

In [122]:
data

array([[ 1.33452146, -0.71888134, -3.16556842,  1.41518756],
       [-2.07614586,  1.53416142, -0.37021066, -0.156386  ],
       [ 0.25862925,  0.24653787, -0.18666713,  1.23972057],
       [ 0.50098281,  2.30627981, -0.47770822, -1.21238371],
       [-0.68956212,  0.02203024, -0.97118628, -1.29340985],
       [-0.20151362,  0.12389771,  1.1599146 ,  1.30603976],
       [-0.96003455, -0.90992736, -0.10247287,  0.15139536]])

In [123]:
n

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [124]:
arr = np.empty((8, 4))

In [125]:
for i in range(8):
    arr[i] = i

arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [126]:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [127]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [128]:
arr = np.arange(32).reshape((8, 4))

In [129]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [130]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [131]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [132]:
arr[[1, 5, 7, 2]]

array([[ 4,  5,  6,  7],
       [20, 21, 22, 23],
       [28, 29, 30, 31],
       [ 8,  9, 10, 11]])

In [133]:
arr[:, [0, 3, 1, 2]]

array([[ 0,  3,  1,  2],
       [ 4,  7,  5,  6],
       [ 8, 11,  9, 10],
       [12, 15, 13, 14],
       [16, 19, 17, 18],
       [20, 23, 21, 22],
       [24, 27, 25, 26],
       [28, 31, 29, 30]])

In [134]:
arr = np.arange(15).reshape((3, 5))

In [135]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [136]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [137]:
np.dot(arr.T, arr)

array([[125, 140, 155, 170, 185],
       [140, 158, 176, 194, 212],
       [155, 176, 197, 218, 239],
       [170, 194, 218, 242, 266],
       [185, 212, 239, 266, 293]])

In [138]:
arr = np.arange(16).reshape((2, 2, 4))

In [139]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [140]:
arr.transpose((1, 0, 2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [141]:
arr.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])