In [1]:
import numpy as np

my_arr = np.arange(1000000)

In [2]:
my_list = list(range(1000000))

In [3]:
%time for _ in range(10): my_arr2 = my_arr*2

CPU times: user 15.8 ms, sys: 7.55 ms, total: 23.4 ms
Wall time: 26 ms


In [4]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: user 529 ms, sys: 92.3 ms, total: 621 ms
Wall time: 620 ms


In [5]:
data = np.random.randn(2, 3)

In [6]:
data

array([[-0.16107661,  0.20926337, -0.48041237],
       [-0.13434018,  0.81716435,  0.0793854 ]])

In [7]:
data * 10

array([[-1.6107661 ,  2.0926337 , -4.80412369],
       [-1.34340182,  8.17164348,  0.79385404]])

In [8]:
data + data

array([[-0.32215322,  0.41852674, -0.96082474],
       [-0.26868036,  1.6343287 ,  0.15877081]])

In [9]:
data.shape

(2, 3)

In [10]:
data.dtype

dtype('float64')

In [11]:
data1 = [6, 7.5, 8, 0, 1]

In [12]:
arr1 = np.array(data1)

In [13]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [14]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

In [15]:
arr2 = np.array(data2)

In [16]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [17]:
 arr2.ndim

2

In [18]:
arr2.shape

(2, 4)

In [19]:
arr1.dtype

dtype('float64')

In [20]:
arr2.dtype

dtype('int64')

In [21]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [23]:
np.empty(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [24]:
np.empty(1)

array([1.])

In [25]:
t = np.arange(15)

In [26]:
t.dtype

dtype('int64')

In [27]:
np.full(1, 10)

array([10])

In [28]:
np.full(10, 23)

array([23, 23, 23, 23, 23, 23, 23, 23, 23, 23])

In [29]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
arr1 = np.array([1, 2, 3], dtype=np.float32)

In [31]:
arr2 = np.array([1, 2, 3], dtype=np.int32)

In [32]:
arr1.dtype

dtype('float32')

In [33]:
arr1 + arr2

array([2., 4., 6.])

In [34]:
arr2.astype(np.float128)

array([1., 2., 3.], dtype=float128)

In [35]:
arr1.astype(np.int32)

array([1, 2, 3], dtype=int32)

In [36]:
nu_string = np.array(['-1.23', '11.2323', '1'])

In [37]:
nu_string

array(['-1.23', '11.2323', '1'], dtype='<U7')

In [38]:
nu_string.astype(np.float128)

array([-1.23  , 11.2323,  1.    ], dtype=float128)

In [39]:
nnn_ = np.array(['adfaf',' 123'])

In [40]:
nnn_

array(['adfaf', ' 123'], dtype='<U5')

In [41]:
nnn_.astype(np.int32)

ValueError: invalid literal for int() with base 10: 'adfaf'

In [ ]:
np.arange(10).astype(np.float)

In [42]:
arr1 * arr1

array([1., 4., 9.], dtype=float32)

In [43]:
arr2

array([1, 2, 3], dtype=int32)

In [44]:
arr1 == arr2

array([ True,  True,  True])

In [45]:
arr1 + arr2

array([2., 4., 6.])

In [46]:
arr = np.arange(100)

In [47]:
arr[10]

10

In [48]:
arr[5:9]

array([5, 6, 7, 8])

In [49]:
arr[0]

0

In [50]:
arr[-1]

99

In [51]:
arr_slice = arr [1:10]

In [52]:
arr_slice[1] = 100

In [53]:
arr[1:14]

array([  1, 100,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13])

In [54]:
arr2 = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [55]:
arr2[2]

array([7, 8, 9])

In [56]:
arr2[1][1]

5

In [57]:
arr2[1, 1]

5

In [58]:
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [59]:
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [60]:
arr3[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [61]:
arr[2]

100

In [62]:
arr3[2]

IndexError: index 2 is out of bounds for axis 0 with size 2

In [63]:
arr3[1]

array([[ 7,  8,  9],
       [10, 11, 12]])

In [64]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [65]:
arr2[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [66]:
arr2[:1]

array([[1, 2, 3]])

In [67]:
arr2[:2, 1:]

array([[2, 3],
       [5, 6]])

In [68]:
arr2[1, :2]

array([4, 5])

In [69]:
arr2[:2, 2]

array([3, 6])

In [70]:
arr2[:, :1]

array([[1],
       [4],
       [7]])

In [71]:
arr2[2:, :]

array([[7, 8, 9]])

In [72]:
arr2[2]

array([7, 8, 9])

In [73]:
arr2[2, :]

array([7, 8, 9])

In [74]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [75]:
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [76]:
old = arr3[0].copy()

In [77]:
arr3[0] = 101

In [78]:
arr3

array([[[101, 101, 101],
        [101, 101, 101]],

       [[  7,   8,   9],
        [ 10,  11,  12]]])

In [79]:
arr3[0] = old

In [80]:
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [81]:
arr3[1, 0]

array([7, 8, 9])

In [82]:
arr3[1, 1]

array([10, 11, 12])

In [83]:
arr3.shape

(2, 2, 3)

In [84]:
arr3[0,0,0]

1

In [85]:
arr1

array([1., 2., 3.], dtype=float32)

In [86]:
arr1 = np.arange(20)

In [87]:
arr1[1:6]

array([1, 2, 3, 4, 5])

In [88]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [89]:
arr2[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [90]:
arr2[2]

array([7, 8, 9])

In [91]:
arr2[:2, 1:]

array([[2, 3],
       [5, 6]])

In [92]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [93]:
arr2[1, :2]

array([4, 5])

In [94]:
arr2[:2, 2]

array([3, 6])

In [95]:
arr2[:, :1]

array([[1],
       [4],
       [7]])

In [96]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [97]:
arr2[:, 1]

array([2, 5, 8])

In [98]:
arr2[:, 1:2]

array([[2],
       [5],
       [8]])

In [99]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [100]:
data = np.random.randn(7, 4)

In [101]:
data

array([[-0.62452576,  0.13591252,  0.2715927 ,  0.27504509],
       [-0.62883448,  0.31011834,  0.11395803,  2.00932916],
       [-0.76073573,  2.26452616,  1.06962589,  0.37015281],
       [ 0.41464087,  0.20833537,  0.28734353, -0.99279874],
       [-1.19085251,  0.11510383, -0.1486986 ,  0.82109061],
       [-0.42901562,  0.16299329, -1.31653236, -1.29321253],
       [-0.12149822,  0.88895276,  0.57223195, -0.574737  ]])

In [102]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [103]:
names[names=='Bob']

array(['Bob', 'Bob'], dtype='<U4')

In [104]:
names=='Bob'

array([ True, False, False,  True, False, False, False])

In [105]:
data[1]

array([-0.62883448,  0.31011834,  0.11395803,  2.00932916])

In [106]:
data[names=='Bob']

array([[-0.62452576,  0.13591252,  0.2715927 ,  0.27504509],
       [ 0.41464087,  0.20833537,  0.28734353, -0.99279874]])

In [107]:
data[[0,3]]

array([[-0.62452576,  0.13591252,  0.2715927 ,  0.27504509],
       [ 0.41464087,  0.20833537,  0.28734353, -0.99279874]])

In [108]:
data[[0, 3], 2:]

array([[ 0.2715927 ,  0.27504509],
       [ 0.28734353, -0.99279874]])

In [109]:
data[names=='Bob', 2:]

array([[ 0.2715927 ,  0.27504509],
       [ 0.28734353, -0.99279874]])

In [110]:
data[names=='Bob', 3]

array([ 0.27504509, -0.99279874])

In [111]:
cond = names == 'Bob'

In [112]:
data[~cond]

array([[-0.62883448,  0.31011834,  0.11395803,  2.00932916],
       [-0.76073573,  2.26452616,  1.06962589,  0.37015281],
       [-1.19085251,  0.11510383, -0.1486986 ,  0.82109061],
       [-0.42901562,  0.16299329, -1.31653236, -1.29321253],
       [-0.12149822,  0.88895276,  0.57223195, -0.574737  ]])

In [113]:
data[names!='Bob']

array([[-0.62883448,  0.31011834,  0.11395803,  2.00932916],
       [-0.76073573,  2.26452616,  1.06962589,  0.37015281],
       [-1.19085251,  0.11510383, -0.1486986 ,  0.82109061],
       [-0.42901562,  0.16299329, -1.31653236, -1.29321253],
       [-0.12149822,  0.88895276,  0.57223195, -0.574737  ]])

In [114]:
mask = (names=='Bob') | (names=='Will')

In [115]:
data[mask]

array([[-0.62452576,  0.13591252,  0.2715927 ,  0.27504509],
       [-0.76073573,  2.26452616,  1.06962589,  0.37015281],
       [ 0.41464087,  0.20833537,  0.28734353, -0.99279874],
       [-1.19085251,  0.11510383, -0.1486986 ,  0.82109061]])

In [116]:
data[~mask]

array([[-0.62883448,  0.31011834,  0.11395803,  2.00932916],
       [-0.42901562,  0.16299329, -1.31653236, -1.29321253],
       [-0.12149822,  0.88895276,  0.57223195, -0.574737  ]])

In [123]:
n = data[mask]
n

array([[-0.62452576,  0.13591252,  0.2715927 ,  0.27504509],
       [-0.76073573,  2.26452616,  1.06962589,  0.37015281],
       [ 0.41464087,  0.20833537,  0.28734353, -0.99279874],
       [-1.19085251,  0.11510383, -0.1486986 ,  0.82109061]])

In [124]:
n[:] = 0

In [125]:
data

array([[-0.62452576,  0.13591252,  0.2715927 ,  0.27504509],
       [-0.62883448,  0.31011834,  0.11395803,  2.00932916],
       [-0.76073573,  2.26452616,  1.06962589,  0.37015281],
       [ 0.41464087,  0.20833537,  0.28734353, -0.99279874],
       [-1.19085251,  0.11510383, -0.1486986 ,  0.82109061],
       [-0.42901562,  0.16299329, -1.31653236, -1.29321253],
       [-0.12149822,  0.88895276,  0.57223195, -0.574737  ]])

In [126]:
n

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])