In [2]:
import numpy as np

In [3]:
arr = np.arange(10)

In [4]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [6]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [8]:
x = np.random.randn(8)
y = np.random.randn(8)

In [9]:
x

array([-0.58582237,  0.55230451, -0.31598172, -0.56289036,  0.19223904,
        0.06451583,  0.5181444 ,  1.30190422])

In [10]:
y

array([ 2.00661175, -0.65039335,  0.05376909,  0.48214275,  0.920104  ,
       -0.11316218, -1.51834736, -0.75014645])

In [11]:
np.maximum(x, y)

array([2.00661175, 0.55230451, 0.05376909, 0.48214275, 0.920104  ,
       0.06451583, 0.5181444 , 1.30190422])

In [12]:
arr = np.random.randn(7) * 5

In [13]:
arr

array([-4.67355232,  3.59249782, -4.44373379, -0.69305818, -3.84948066,
       -1.10839891,  1.18712687])

In [14]:
remainder, whole_part = np.modf(arr)

In [15]:
remainder

array([-0.67355232,  0.59249782, -0.44373379, -0.69305818, -0.84948066,
       -0.10839891,  0.18712687])

In [17]:
whole_part

array([-4.,  3., -4., -0., -3., -1.,  1.])

In [18]:
arr

array([-4.67355232,  3.59249782, -4.44373379, -0.69305818, -3.84948066,
       -1.10839891,  1.18712687])

In [19]:
np.sqrt(arr)

/home/arti/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([       nan, 1.89538857,        nan,        nan,        nan,
              nan, 1.08955352])

In [20]:
np.sqrt(arr, arr)

/home/arti/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([       nan, 1.89538857,        nan,        nan,        nan,
              nan, 1.08955352])

In [21]:
arr

array([       nan, 1.89538857,        nan,        nan,        nan,
              nan, 1.08955352])