In [2]:
import numpy as np

x = np.array([[1., 2., 3], [4, 5, 6]])
y = np.array([[6, 23.], [-1, 7], [8, 9]])

In [3]:
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [4]:
y

array([[ 6., 23.],
       [-1.,  7.],
       [ 8.,  9.]])

In [5]:
x.dot(y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [6]:
x*y

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [8]:
x.sum(axis=0)

array([5., 7., 9.])

In [9]:
x.sum(axis=1)

array([ 6., 15.])

In [10]:
x @ y

array([[ 28.,  64.],
       [ 67., 181.]])

In [11]:
from numpy.linalg import inv, qr

In [12]:
X = np.random.randn(5, 5)

In [14]:
mat = X.T @ X

In [16]:
inv(mat)

array([[ 0.23386908,  0.11791158, -0.10425763,  0.04536632, -0.05906175],
       [ 0.11791158,  1.6423332 , -0.54777411,  1.8254968 ,  0.5431753 ],
       [-0.10425763, -0.54777411,  0.33760141, -0.58586211, -0.18780841],
       [ 0.04536632,  1.8254968 , -0.58586211,  3.07967305,  1.54761877],
       [-0.05906175,  0.5431753 , -0.18780841,  1.54761877,  1.35719955]])

In [17]:
mat @ inv(mat)

array([[ 1.00000000e+00, -1.04319741e-16, -5.66188801e-17,
        -3.77103461e-17, -7.90426839e-18],
       [-8.36885804e-17,  1.00000000e+00, -7.62325056e-17,
         3.66257192e-16,  1.70946580e-17],
       [-5.39911138e-17, -1.87743350e-16,  1.00000000e+00,
         4.36453098e-17, -1.26938936e-16],
       [ 4.79104776e-17,  5.89195821e-16,  7.71715866e-17,
         1.00000000e+00, -1.08424566e-16],
       [-4.70952400e-17, -2.25281926e-16,  4.38640970e-17,
        -6.62814841e-17,  1.00000000e+00]])

In [18]:
mat.dot(inv(mat))

array([[ 1.00000000e+00, -1.04319741e-16, -5.66188801e-17,
        -3.77103461e-17, -7.90426839e-18],
       [-8.36885804e-17,  1.00000000e+00, -7.62325056e-17,
         3.66257192e-16,  1.70946580e-17],
       [-5.39911138e-17, -1.87743350e-16,  1.00000000e+00,
         4.36453098e-17, -1.26938936e-16],
       [ 4.79104776e-17,  5.89195821e-16,  7.71715866e-17,
         1.00000000e+00, -1.08424566e-16],
       [-4.70952400e-17, -2.25281926e-16,  4.38640970e-17,
        -6.62814841e-17,  1.00000000e+00]])

In [19]:
q, r = qr(mat)

In [20]:
r

array([[-5.76900387, -1.85501763, -5.21767396,  0.81157498, -1.22298555],
       [ 0.        , -6.17411653, -4.60240906,  5.04284702, -4.16838306],
       [ 0.        ,  0.        , -4.74122023, -1.85245606,  1.65531547],
       [ 0.        ,  0.        ,  0.        , -0.7724    ,  1.34602268],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.46773349]])

In [21]:
q

array([[-0.91488755,  0.2268038 ,  0.31250342, -0.1145394 , -0.02762516],
       [-0.05145072, -0.67733765,  0.11459154, -0.67888746,  0.25406128],
       [-0.38968487, -0.34331421, -0.82624098,  0.19972551, -0.08784428],
       [ 0.01546048,  0.50479933, -0.36546042, -0.29560951,  0.72387313],
       [-0.09077599, -0.34217939,  0.27013869,  0.63144064,  0.63480768]])