In [1]:
import numpy as np

In [2]:
arr = np.arange(8)
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [3]:
arr.reshape((4,2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [4]:
arr.reshape((4, 2)).reshape((2, 4))

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [7]:
arr2 = np.arange(12)
arr2.reshape((4,3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [8]:
arr2.reshape((4,3), order='F')

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [9]:
arr.reshape((4,-1))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [10]:
other_arr = np.ones((3, 5))

other_arr.shape

(3, 5)

In [11]:
arr3 = np.arange(15)

In [12]:
arr3.reshape(other_arr.shape)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [14]:
arr4 = np.arange(15).reshape((5, 3))
arr4

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [16]:
arr4.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [17]:
arr4.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [19]:
arr = np.arange(12).reshape((3,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [20]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [21]:
arr.ravel('F')

array([ 0,  4,  8,  1,  5,  9,  2,  6, 10,  3,  7, 11])

In [22]:
arr.ravel('A')

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [23]:
arr.ravel('K')

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [24]:
arr[0][0]

0

In [25]:
arr[1][0]

4

In [26]:
arr[0][1]

1

In [27]:
arr1 = np.array([[1,2,3], [4,5,6]])
arr2 = np.array([[7,8,9], [10,11,12]])
np.concatenate([arr1, arr2])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [28]:
np.concatenate([arr1, arr2], axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [32]:
np.vstack((arr1, arr2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [33]:
np.hstack((arr1, arr2))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [34]:
arr = np.random.randn(5, 2)
arr

array([[-0.3069153 ,  0.22662133],
       [ 2.31373416,  0.22312157],
       [-0.40027923,  0.07313185],
       [ 1.49657538,  1.63887878],
       [ 0.86378287,  1.1612717 ]])

In [35]:
first, second, third = np.split(arr, [1, 3])

In [36]:
first

array([[-0.3069153 ,  0.22662133]])

In [37]:
second

array([[ 2.31373416,  0.22312157],
       [-0.40027923,  0.07313185]])

In [38]:
third

array([[1.49657538, 1.63887878],
       [0.86378287, 1.1612717 ]])

In [48]:
np.split(arr, [1, 3])

[array([[-0.3069153 ,  0.22662133]]),
 array([[ 2.31373416,  0.22312157],
        [-0.40027923,  0.07313185]]),
 array([[1.49657538, 1.63887878],
        [0.86378287, 1.1612717 ]])]

In [50]:
arr = np.arange(6)
arr1 = arr.reshape((3, 2))
arr2 = np.random.randn(3, 2)
np.r_[arr1, arr2]

array([[ 0.        ,  1.        ],
       [ 2.        ,  3.        ],
       [ 4.        ,  5.        ],
       [-0.94232562, -0.44831389],
       [ 0.22021379, -0.47512513],
       [-0.14934935, -0.16604745]])

In [51]:
np.c_[np.r_[arr1, arr2], arr]

array([[ 0.        ,  1.        ,  0.        ],
       [ 2.        ,  3.        ,  1.        ],
       [ 4.        ,  5.        ,  2.        ],
       [-0.94232562, -0.44831389,  3.        ],
       [ 0.22021379, -0.47512513,  4.        ],
       [-0.14934935, -0.16604745,  5.        ]])

In [52]:
np.c_[1:6, -10:-5]

array([[  1, -10],
       [  2,  -9],
       [  3,  -8],
       [  4,  -7],
       [  5,  -6]])

In [54]:
arr = np.arange(3)
arr

array([0, 1, 2])

In [55]:
arr.repeat(3)

array([0, 0, 0, 1, 1, 1, 2, 2, 2])

In [58]:
arr = np.arange(4).reshape((2, 2))
arr

array([[0, 1],
       [2, 3]])

In [59]:
arr.repeat(3)

array([0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3])

In [60]:
arr = np.arange(3)
arr.repeat([2,3,4])

array([0, 0, 1, 1, 1, 2, 2, 2, 2])

In [61]:
arr = np.random.randn(2, 2)
arr

array([[-0.02292881,  1.13696676],
       [-1.80333531,  2.78272628]])

In [62]:
arr.repeat(2, axis=0)

array([[-0.02292881,  1.13696676],
       [-0.02292881,  1.13696676],
       [-1.80333531,  2.78272628],
       [-1.80333531,  2.78272628]])

In [63]:
arr.repeat(2, axis=1)

array([[-0.02292881, -0.02292881,  1.13696676,  1.13696676],
       [-1.80333531, -1.80333531,  2.78272628,  2.78272628]])

In [64]:
arr.repeat([2, 3], axis=0)

array([[-0.02292881,  1.13696676],
       [-0.02292881,  1.13696676],
       [-1.80333531,  2.78272628],
       [-1.80333531,  2.78272628],
       [-1.80333531,  2.78272628]])

In [65]:
arr.repeat([2, 3], axis=1)

array([[-0.02292881, -0.02292881,  1.13696676,  1.13696676,  1.13696676],
       [-1.80333531, -1.80333531,  2.78272628,  2.78272628,  2.78272628]])

In [66]:
arr

array([[-0.02292881,  1.13696676],
       [-1.80333531,  2.78272628]])

In [68]:
np.tile(arr, 2)

array([[-0.02292881,  1.13696676, -0.02292881,  1.13696676],
       [-1.80333531,  2.78272628, -1.80333531,  2.78272628]])

In [69]:
np.tile(arr, (2, 1))

array([[-0.02292881,  1.13696676],
       [-1.80333531,  2.78272628],
       [-0.02292881,  1.13696676],
       [-1.80333531,  2.78272628]])

In [71]:
np.tile(arr, (3, 2))

array([[-0.02292881,  1.13696676, -0.02292881,  1.13696676],
       [-1.80333531,  2.78272628, -1.80333531,  2.78272628],
       [-0.02292881,  1.13696676, -0.02292881,  1.13696676],
       [-1.80333531,  2.78272628, -1.80333531,  2.78272628],
       [-0.02292881,  1.13696676, -0.02292881,  1.13696676],
       [-1.80333531,  2.78272628, -1.80333531,  2.78272628]])

In [72]:
arr = np.arange(10) * 100
inds = [7, 1, 2 ,6]
arr[inds]

array([700, 100, 200, 600])

In [73]:
arr.take(inds)

array([700, 100, 200, 600])

In [74]:
arr.put(inds, 42)

In [75]:
arr

array([  0,  42,  42, 300, 400, 500,  42,  42, 800, 900])

In [76]:
arr.put(inds, [40, 41, 42, 43])
arr

array([  0,  41,  42, 300, 400, 500,  43,  40, 800, 900])

In [77]:
inds = [2, 0, 2, 1]
arr = np.random.randn(2, 4)
arr

array([[-1.02301822, -0.40139464, -1.39087878, -0.80854582],
       [ 0.8997776 ,  2.10862324, -0.05645868, -0.84386172]])

In [78]:
arr.take(inds, axis=1)

array([[-1.39087878, -1.02301822, -1.39087878, -0.40139464],
       [-0.05645868,  0.8997776 , -0.05645868,  2.10862324]])