In [1]:
import numpy as np

In [2]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [3]:
arr * 4

array([ 0,  4,  8, 12, 16])

In [4]:
arr = np.random.randn(4, 3)
arr.mean(0)

array([-0.15373317,  0.32427866,  0.06514987])

In [5]:
arr

array([[-0.92560881, -0.51210131,  0.79129696],
       [-0.23260229, -0.46928457,  0.32721845],
       [ 0.50739957,  2.44560103, -1.01002339],
       [ 0.03587887, -0.16710051,  0.15210747]])

In [6]:
arr.mean(axis=1)

array([-0.21547105, -0.12488947,  0.64765907,  0.00696194])

In [7]:
arr.mean(axis=0)

array([-0.15373317,  0.32427866,  0.06514987])

In [8]:
demeaned = arr - arr.mean(0)
demeaned

array([[-0.77187565, -0.83637997,  0.72614709],
       [-0.07886913, -0.79356323,  0.26206857],
       [ 0.66113274,  2.12132237, -1.07517326],
       [ 0.18961204, -0.49137917,  0.0869576 ]])

In [9]:
demeaned.mean(0)

array([ 0.00000000e+00, -5.55111512e-17, -3.46944695e-17])

In [10]:
row_means = arr.mean(1)
row_means

array([-0.21547105, -0.12488947,  0.64765907,  0.00696194])

In [11]:
row_means.shape

(4,)

In [12]:
row_means.reshape((4,1))
demeaned = arr - row_means.reshape((4, 1))
demeaned.mean(1)

array([ 0.00000000e+00,  1.85037171e-17, -7.40148683e-17,  9.25185854e-18])

In [13]:
arr

array([[-0.92560881, -0.51210131,  0.79129696],
       [-0.23260229, -0.46928457,  0.32721845],
       [ 0.50739957,  2.44560103, -1.01002339],
       [ 0.03587887, -0.16710051,  0.15210747]])

In [14]:
arr - arr.mean(1).reshape((4, 1))

array([[-0.71013776, -0.29663025,  1.00676802],
       [-0.10771282, -0.3443951 ,  0.45210792],
       [-0.1402595 ,  1.79794196, -1.65768246],
       [ 0.02891693, -0.17406245,  0.14514553]])

In [22]:
arr = np.zeros((4, 4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
arr_3d = arr[:, np.newaxis, :]
arr_3d.shape

(4, 1, 4)

In [23]:
arr_3d

array([[[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]]])

In [24]:
arr_1d = np.random.normal(size=3)
arr_1d

array([-0.96957987,  1.61062783,  0.37099096])

In [19]:
arr_1d[:, np.newaxis]

array([[-0.36912864],
       [-2.60948908],
       [-1.27372352]])

In [20]:
arr_1d[np.newaxis, :]

array([[-0.36912864, -2.60948908, -1.27372352]])

In [27]:
arr = np.random.randn(3, 4, 5)
arr

array([[[-0.91398396,  1.02332978, -0.76491644, -0.27008016,
          1.47158146],
        [-0.43532776, -0.96076205,  1.04567586,  0.63079224,
          0.81487533],
        [-0.30445195, -1.98398144, -0.23135256,  0.88246893,
         -0.02953912],
        [ 0.84961355, -0.67064151,  0.72118998,  1.99674143,
         -0.68721228]],

       [[-1.82463153,  0.4946112 , -0.42155705, -0.55148349,
         -0.76508069],
        [-2.51677988,  1.14736029,  0.19323702, -0.93153346,
         -1.10710223],
        [-2.00291442,  1.55795716,  2.07591843, -0.37327651,
         -0.8301183 ],
        [-0.09331876, -1.57632478, -1.4207618 ,  2.49792416,
          0.03217287]],

       [[-1.35622346,  2.03753293,  0.6207344 ,  0.28218784,
          0.79870129],
        [ 2.94589585,  0.11314172,  1.74190164, -1.09239603,
          0.80835579],
        [ 0.42293571,  0.74157131,  1.62395027,  0.31229791,
         -0.3313858 ],
        [-0.27532247,  0.39458721,  1.09239878, -0.03246003,
         -0

In [28]:
arr.shape

(3, 4, 5)

In [29]:
depth_means = arr.mean(2)
depth_means

array([[ 0.10918614,  0.21905072, -0.33337123,  0.44193824],
       [-0.61362831, -0.64296365,  0.08551327, -0.11206166],
       [ 0.4765866 ,  0.90337979,  0.55387388,  0.15689362]])

In [30]:
depth_means.shape

(3, 4)

In [31]:
demeaned = arr - depth_means[:, :, np.newaxis]
demeaned

array([[[-1.0231701 ,  0.91414364, -0.87410258, -0.3792663 ,
          1.36239533],
        [-0.65437848, -1.17981277,  0.82662513,  0.41174152,
          0.5958246 ],
        [ 0.02891928, -1.65061021,  0.10201867,  1.21584016,
          0.3038321 ],
        [ 0.40767532, -1.11257974,  0.27925174,  1.55480319,
         -1.12915052]],

       [[-1.21100322,  1.10823951,  0.19207127,  0.06214482,
         -0.15145238],
        [-1.87381623,  1.79032395,  0.83620067, -0.28856981,
         -0.46413858],
        [-2.08842769,  1.47244389,  1.99040515, -0.45878979,
         -0.91563157],
        [ 0.0187429 , -1.46426312, -1.30870014,  2.60998583,
          0.14423453]],

       [[-1.83281006,  1.56094633,  0.1441478 , -0.19439876,
          0.32211469],
        [ 2.04251605, -0.79023807,  0.83852184, -1.99577582,
         -0.095024  ],
        [-0.13093817,  0.18769743,  1.07007639, -0.24157597,
         -0.88525968],
        [-0.43221609,  0.23769359,  0.93550516, -0.18935364,
         -0

In [32]:
demeaned.mean(2)

array([[-4.44089210e-17,  0.00000000e+00,  2.22044605e-17,
         0.00000000e+00],
       [-2.22044605e-17,  0.00000000e+00,  8.88178420e-17,
         6.66133815e-17],
       [ 0.00000000e+00,  4.44089210e-17,  4.44089210e-17,
         2.22044605e-17]])

In [33]:
def demean_axis(arr, axis=0):
    means = arr.mean(axis)
    
    indexer = [slice(None)] * arr.ndim
    indexer[axis] = np.newaxis
    return arr - means[indexer]

In [34]:
x = demean_axis(arr, axis=2)

/home/arti/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:6: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  


In [35]:
x.mean(2)

array([[-4.44089210e-17,  0.00000000e+00,  2.22044605e-17,
         0.00000000e+00],
       [-2.22044605e-17,  0.00000000e+00,  8.88178420e-17,
         6.66133815e-17],
       [ 0.00000000e+00,  4.44089210e-17,  4.44089210e-17,
         2.22044605e-17]])

In [36]:
arr = np.zeros((4, 3))
arr[:] = 5

In [37]:
arr

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [38]:
col = np.array([1.28, -0.42, 0.44, 1.6])
arr[:] = col[:, np.newaxis]
arr

array([[ 1.28,  1.28,  1.28],
       [-0.42, -0.42, -0.42],
       [ 0.44,  0.44,  0.44],
       [ 1.6 ,  1.6 ,  1.6 ]])

In [39]:
col[:, np.newaxis]

array([[ 1.28],
       [-0.42],
       [ 0.44],
       [ 1.6 ]])

In [40]:
arr[:2] = [[-1.37], [0.509]]
arr

array([[-1.37 , -1.37 , -1.37 ],
       [ 0.509,  0.509,  0.509],
       [ 0.44 ,  0.44 ,  0.44 ],
       [ 1.6  ,  1.6  ,  1.6  ]])