In [1]:
import numpy as np

In [2]:
arr = np.arange(10)
np.add.reduce(arr)

45

In [3]:
arr.sum()

45

In [4]:
np.random.seed(12346)

In [8]:
arr = np.random.randn(5, 5)
arr[::2].sort(1)
arr

array([[-1.08232609e-01,  5.48599204e-02,  1.02713364e-01,
         1.06416038e-01,  5.22417588e-01],
       [ 1.96365303e-01, -1.93872621e-01, -1.45657748e+00,
         8.57447625e-01, -7.41575581e-01],
       [-1.28346227e+00, -7.80362529e-01, -1.06424500e-01,
         4.77960478e-01,  5.93712721e-01],
       [ 1.29244703e+00,  1.51649202e-01, -1.46631428e+00,
        -1.43337431e+00, -9.77525491e-02],
       [-1.83245736e-01, -7.05498872e-04,  1.35506346e-01,
         2.53602483e-01,  1.23514614e+00]])

In [6]:
arr[:, :-1] < arr[:, 1:]

array([[ True,  True,  True,  True],
       [False,  True, False, False],
       [ True,  True,  True,  True],
       [ True, False,  True,  True],
       [ True,  True,  True,  True]])

In [7]:
np.logical_and.reduce(arr[:, :-1] < arr[:, 1:], axis=1)

array([ True, False,  True, False,  True])

In [9]:
arr = np.arange(15).reshape((3, 5))
np.add.accumulate(arr, axis=1)

array([[ 0,  1,  3,  6, 10],
       [ 5, 11, 18, 26, 35],
       [10, 21, 33, 46, 60]])

In [10]:
arr = np.arange(3).repeat([1, 2, 2])
arr

array([0, 1, 1, 2, 2])

In [12]:
np.multiply.outer(arr, np.arange(5))

array([[0, 0, 0, 0, 0],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 2, 4, 6, 8],
       [0, 2, 4, 6, 8]])

In [13]:
x, y = np.random.randn(3, 4), np.random.randn(5)
result = np.subtract.outer(x, y)
result.shape

(3, 4, 5)

In [14]:
arr = np.arange(10)
np.add.reduceat(arr, [0, 5, 8])

array([10, 18, 17])

In [15]:
arr = np.multiply.outer(np.arange(4), np.arange(5))
arr

array([[ 0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4],
       [ 0,  2,  4,  6,  8],
       [ 0,  3,  6,  9, 12]])

In [16]:
np.add.reduceat(arr, [0, 2, 4], axis=1)

array([[ 0,  0,  0],
       [ 1,  5,  4],
       [ 2, 10,  8],
       [ 3, 15, 12]])

In [18]:
def add_elements(x, y):
    return x + y

In [19]:
add_them = np.frompyfunc(add_elements, 2, 1)
add_them(np.arange(8), np.arange(8))

array([0, 2, 4, 6, 8, 10, 12, 14], dtype=object)

In [21]:
add_them = np.vectorize(add_elements, otypes=[np.float64])
add_them(np.arange(8), np.arange(8))

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14.])

In [22]:
arr = np.random.randn(10000)
%timeit add_them(arr, arr)

1.33 ms ± 50.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [23]:
%timeit np.add(arr, arr)

3.1 µs ± 21.8 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
