In [1]:
import numpy as np

In [2]:
arr = np.random.randn(6)

In [3]:
arr

array([ 1.04356509,  0.95370967, -2.2096724 , -0.04826034,  0.83237098,
        0.13291996])

In [5]:
arr.sort()
arr

array([-2.2096724 , -0.04826034,  0.13291996,  0.83237098,  0.95370967,
        1.04356509])

In [6]:
arr = np.random.randn(3, 5)
arr

array([[-0.42166978,  2.45644464, -0.11406063, -0.40877609, -0.63423309],
       [-1.80958474,  0.41833312,  0.88814946,  0.53833429, -0.21268004],
       [-1.55435358,  1.04336753,  1.24005798,  0.32490053,  1.22686789]])

In [7]:
arr[:, 0].sort()
arr

array([[-1.80958474,  2.45644464, -0.11406063, -0.40877609, -0.63423309],
       [-1.55435358,  0.41833312,  0.88814946,  0.53833429, -0.21268004],
       [-0.42166978,  1.04336753,  1.24005798,  0.32490053,  1.22686789]])

In [8]:
arr = np.random.randn(5)
arr

array([ 0.65867614,  0.02235562, -1.47895794, -0.17472571,  0.55382617])

In [9]:
np.sort(arr)

array([-1.47895794, -0.17472571,  0.02235562,  0.55382617,  0.65867614])

In [10]:
arr

array([ 0.65867614,  0.02235562, -1.47895794, -0.17472571,  0.55382617])

In [11]:
arr = np.random.randn(3, 5)
arr

array([[ 1.00727967, -0.24978157,  1.75761884,  0.44588795,  0.96666531],
       [-0.60224915, -0.95460596, -0.28636314,  1.12936409, -0.44312969],
       [-0.96454095, -1.07369663,  0.23615344,  1.07411394,  0.79125762]])

In [12]:
arr.sort(axis=1)

In [13]:
arr

array([[-0.24978157,  0.44588795,  0.96666531,  1.00727967,  1.75761884],
       [-0.95460596, -0.60224915, -0.44312969, -0.28636314,  1.12936409],
       [-1.07369663, -0.96454095,  0.23615344,  0.79125762,  1.07411394]])

In [15]:
arr.sort(axis=0)
arr

array([[-1.07369663, -0.96454095, -0.44312969, -0.28636314,  1.07411394],
       [-0.95460596, -0.60224915,  0.23615344,  0.79125762,  1.12936409],
       [-0.24978157,  0.44588795,  0.96666531,  1.00727967,  1.75761884]])

In [16]:
arr[:, ::-1]

array([[ 1.07411394, -0.28636314, -0.44312969, -0.96454095, -1.07369663],
       [ 1.12936409,  0.79125762,  0.23615344, -0.60224915, -0.95460596],
       [ 1.75761884,  1.00727967,  0.96666531,  0.44588795, -0.24978157]])

In [17]:
values = np.array([5, 0, 1, 3, 2])
indexer = values.argsort()
indexer

array([1, 2, 4, 3, 0])

In [18]:
values[indexer]

array([0, 1, 2, 3, 5])

In [19]:
arr = np.random.randn(3, 5)
arr[0] = values

In [20]:
arr

array([[ 5.        ,  0.        ,  1.        ,  3.        ,  2.        ],
       [ 1.35756938,  0.71746199, -0.07464409, -1.56637738,  1.57709436],
       [-1.11988481,  0.10969991, -1.77947024,  0.16713185, -1.07734798]])

In [21]:
arr[:, arr[0].argsort()]

array([[ 0.        ,  1.        ,  2.        ,  3.        ,  5.        ],
       [ 0.71746199, -0.07464409,  1.57709436, -1.56637738,  1.35756938],
       [ 0.10969991, -1.77947024, -1.07734798,  0.16713185, -1.11988481]])

In [22]:
first_name = np.array(['Bob', 'Jane', 'Steve', 'Bill', 'Barbara'])
last_name = np.array(['Jones', 'Arnold', 'Arnold', 'Jones', 'Walters'])

In [23]:
sorter = np.lexsort((first_name, last_name))
sorter

array([1, 2, 3, 0, 4])

In [28]:
for i in zip(last_name[sorter], first_name[sorter]):
    print(i)

('Arnold', 'Jane')
('Arnold', 'Steve')
('Jones', 'Bill')
('Jones', 'Bob')
('Walters', 'Barbara')


In [26]:
last_name[sorter]

array(['Arnold', 'Arnold', 'Jones', 'Jones', 'Walters'], dtype='<U7')

In [27]:
first_name[sorter]

array(['Jane', 'Steve', 'Bill', 'Bob', 'Barbara'], dtype='<U7')

In [29]:
values = np.array(['2:first', '2:second', '1:first', '1:second', '1: third'])
key=np.array([2,2,1,1,1])
indexer = key.argsort(kind='mergesort')
indexer

array([2, 3, 4, 0, 1])

In [30]:
values.take(indexer)

array(['1:first', '1:second', '1: third', '2:first', '2:second'],
      dtype='<U8')

In [31]:
np.random.seed(12345)
arr = np.random.randn(20)
arr

array([-0.20470766,  0.47894334, -0.51943872, -0.5557303 ,  1.96578057,
        1.39340583,  0.09290788,  0.28174615,  0.76902257,  1.24643474,
        1.00718936, -1.29622111,  0.27499163,  0.22891288,  1.35291684,
        0.88642934, -2.00163731, -0.37184254,  1.66902531, -0.43856974])

In [32]:
np.partition(arr,3)

array([-2.00163731, -1.29622111, -0.5557303 , -0.51943872, -0.37184254,
       -0.43856974, -0.20470766,  0.28174615,  0.76902257,  0.47894334,
        1.00718936,  0.09290788,  0.27499163,  0.22891288,  1.35291684,
        0.88642934,  1.39340583,  1.96578057,  1.66902531,  1.24643474])

In [33]:
indieces = np.argpartition(arr, 3)
indieces

array([16, 11,  3,  2, 17, 19,  0,  7,  8,  1, 10,  6, 12, 13, 14, 15,  5,
        4, 18,  9])

In [34]:
arr.take(indieces)

array([-2.00163731, -1.29622111, -0.5557303 , -0.51943872, -0.37184254,
       -0.43856974, -0.20470766,  0.28174615,  0.76902257,  0.47894334,
        1.00718936,  0.09290788,  0.27499163,  0.22891288,  1.35291684,
        0.88642934,  1.39340583,  1.96578057,  1.66902531,  1.24643474])

In [35]:
arr = np.array([0, 1, 7, 12, 15])
arr.searchsorted(9)

3

In [36]:
arr.searchsorted([0, 8, 11, 16])

array([0, 3, 3, 5])

In [37]:
arr = np.array([0,0,0,1,1,1,1])
arr.searchsorted([0, 1])

array([0, 3])

In [38]:
arr.searchsorted([0, 1], side='right')

array([3, 7])

In [39]:
data = np.floor(np.random.uniform(0, 10000, size=50))
bins = np.array([0, 100, 1000, 5000, 10000])
data

array([9940., 6768., 7908., 1709.,  268., 8003., 9037.,  246., 4917.,
       5262., 5963.,  519., 8950., 7282., 8183., 5002., 8101.,  959.,
       2189., 2587., 4681., 4593., 7095., 1780., 5314., 1677., 7688.,
       9281., 6094., 1501., 4896., 3773., 8486., 9110., 3838., 3154.,
       5683., 1878., 1258., 6875., 7996., 5735., 9732., 6340., 8884.,
       4954., 3516., 7142., 5039., 2256.])

In [41]:
labels = bins.searchsorted(data)
labels

array([4, 4, 4, 3, 2, 4, 4, 2, 3, 4, 4, 2, 4, 4, 4, 4, 4, 2, 3, 3, 3, 3,
       4, 3, 4, 3, 4, 4, 4, 3, 3, 3, 4, 4, 3, 3, 4, 3, 3, 4, 4, 4, 4, 4,
       4, 3, 3, 4, 4, 3])

In [43]:
import pandas as pd

In [44]:
pd.Series(data).groupby(labels).mean()

2     498.000000
3    3064.277778
4    7389.035714
dtype: float64