In [1]:
import pandas as pd
from pandas import Series, DataFrame

In [2]:
obj = pd.Series([4, 7, 5, -3])

In [3]:
obj

0    4
1    7
2    5
3   -3
dtype: int64

In [4]:
obj.values

array([ 4,  7,  5, -3])

In [5]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [6]:
obj2 = pd.Series([4, 1, 2, 9], index=['a', 'b', 'c', 'd'])

In [7]:
obj2

a    4
b    1
c    2
d    9
dtype: int64

In [8]:
obj2['a']

4

In [9]:
obj2['a'] = 3

In [10]:
obj2

a    3
b    1
c    2
d    9
dtype: int64

In [12]:
obj2[['a', 'b','c']]

a    3
b    1
c    2
dtype: int64

In [13]:
obj2[obj2 > 0]

a    3
b    1
c    2
d    9
dtype: int64

In [14]:
obj[obj > 0]

0    4
1    7
2    5
dtype: int64

In [15]:
obj2 - 2

a    1
b   -1
c    0
d    7
dtype: int64

In [16]:
import numpy as np

In [17]:
np.exp(obj2)

a      20.085537
b       2.718282
c       7.389056
d    8103.083928
dtype: float64

In [18]:
'b' in obj2

True

In [19]:
'f' in obj2

False

In [21]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [22]:
obj3 = pd.Series(sdata)

In [23]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [24]:
states = ['California', 'Ohio', 'Oregon', 'Texas']

In [26]:
obj4 = pd.Series(sdata, index=states)

In [27]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [28]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [29]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [30]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [31]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [32]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [36]:
obj4.name = 'population'

In [37]:
obj4.index.name = 'state'

In [38]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [39]:
obj

0    4
1    7
2    5
3   -3
dtype: int64

In [40]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']

In [41]:
obj

Bob      4
Steve    7
Jeff     5
Ryan    -3
dtype: int64

In [44]:
 data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

frame1 = pd.DataFrame(data)

In [45]:
frame1

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [46]:
frame1.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [47]:
pd.DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [48]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
                     index=['one', 'two', 'three', 'four', 'five', 'six'])

In [49]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [50]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [52]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [53]:
frame2.state

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [54]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [55]:
frame2['debt'] = 16.5

In [56]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [57]:
frame2['debt'] = np.random.randn(6)

In [58]:
frame2

year   state  pop      debt
one    2000    Ohio  1.5  0.745458
two    2001    Ohio  1.7 -0.956256
three  2002    Ohio  3.6  0.499860
four   2001  Nevada  2.4  0.094424
five   2002  Nevada  2.9  1.277391
six    2003  Nevada  3.2  0.047047

In [59]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])

In [60]:
frame2['debt'] = val

In [61]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [62]:
frame2['eastern'] = frame2.state == 'Ohio'

In [63]:
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [64]:
del frame2['eastern']

In [65]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [66]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [67]:
pop = {'Nevada': {2001: 2.4, 2002:2.9},
      'Ohio': {2000:1.5, 2001:1.7, 2002:3.6}}

In [68]:
frame3 = pd.DataFrame(pop)

In [69]:
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [70]:
frame3.T

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [73]:
pd.DataFrame(pop, index=[2000, 2001, 2002, 2003])

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [74]:
pdata = {'Ohio': frame3['Ohio'][:-1],
        'Nevada': frame3['Nevada'][:2]}

In [75]:
pd.DataFrame(pdata)

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9

In [76]:
frame3['Ohio'][:-1]

2001    1.7
2002    3.6
Name: Ohio, dtype: float64

In [77]:
frame3['Nevada'][:2]

2001    2.4
2002    2.9
Name: Nevada, dtype: float64

In [78]:
frame3.index.name = 'year';
frame3.columns.name = 'state'

In [79]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [80]:
frame3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [81]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

In [82]:
obj1 = pd.Series(range(3), index=['a','b','c'])

In [83]:
index = obj1.index

In [84]:
index

Index(['a', 'b', 'c'], dtype='object')

In [85]:
index[1:]

Index(['b', 'c'], dtype='object')

In [86]:
labels = pd.Index(np.arange(3))

In [87]:
labels

Int64Index([0, 1, 2], dtype='int64')

In [88]:
obj2 = pd.Series([1.5, -2.5, 0], index=labels)

In [89]:
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [91]:
obj2.index is labels

True

In [92]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [95]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [96]:
'Ohio' in frame3.columns

True

In [98]:
2001 in frame3.index

True

In [99]:
dup_labels = pd.Index(['foo', 'foo', 'bar', 'bar'])

In [100]:
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')