In [1]:
import pandas as pd
import numpy as np

In [2]:
obj1 = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d','b', 'a', 'c'])
obj1

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [3]:
obj2 = obj1.reindex(['a', 'b', 'c', 'd', 'e'])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [4]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])
obj3

0      blue
2    purple
4    yellow
dtype: object

In [5]:
obj3.reindex(range(6), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [6]:
frame1 = pd.DataFrame(np.arange(9).reshape((3,3)),
                     index=['a', 'b', 'c'],
                     columns=['Ohio', 'Texas', 'California'])
frame1

Ohio  Texas  California
a     0      1           2
b     3      4           5
c     6      7           8

In [7]:
frame2 = frame1.reindex(['a', 'b', 'c', 'd'])
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   3.0    4.0         5.0
c   6.0    7.0         8.0
d   NaN    NaN         NaN

In [8]:
states = ['Texas', 'Utah', 'California']

In [9]:
frame1.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
b      4   NaN           5
c      7   NaN           8

In [10]:
frame1.loc[['a', 'b', 'c', 'd'], states]

KeyError: 'Passing list-likes to .loc or [] with any missing labels is no longer supported, see https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#deprecate-loc-reindex-listlike'

In [ ]:
frame1.loc[['a', 'b', 'c'], ['Ohio', 'Texas', 'California']]

In [11]:
obj1 = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])
obj1

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [12]:
obj2 = obj1.drop('c')
obj2

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [13]:
obj1.drop(['d', 'c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [14]:
obj1

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [15]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [16]:
data.drop(['Ohio','Utah'])

one  two  three  four
Colorado    4    5      6     7
New York   12   13     14    15

In [17]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [18]:
data.drop('two', axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [19]:
data.drop(['two', 'four'], axis='columns')

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [20]:
obj1.drop('c', inplace=True)

In [21]:
obj1

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [22]:
obj1

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [23]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [24]:
obj1 = pd.Series(np.arange(4.), index=['a', 'b', 'c', 'd'])
obj1

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [25]:
obj1['b']

1.0

In [26]:
obj1[2:4]

c    2.0
d    3.0
dtype: float64

In [27]:
obj1[['a', 'c']]

a    0.0
c    2.0
dtype: float64

In [29]:
obj1[[1, 3]]

b    1.0
d    3.0
dtype: float64

In [30]:
obj1[obj1 < 3]

a    0.0
b    1.0
c    2.0
dtype: float64

In [31]:
obj1['b': 'c']

b    1.0
c    2.0
dtype: float64

In [32]:
obj1['b':'c'] = 5
obj1

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [33]:
obj1[2:3] = 2
obj1

a    0.0
b    5.0
c    2.0
d    3.0
dtype: float64

In [34]:
data1 = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])
data1

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [35]:
data1['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64

In [36]:
data1[['three', 'one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [37]:
data1[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [40]:
data1[data1['three'] > 5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [41]:
data1 < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [43]:
data1[data1 < 5] = 0
data1

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [44]:
data1.loc['Colorado', ['two', 'three']]

two      5
three    6
Name: Colorado, dtype: int64

In [45]:
data1.iloc[2, [3, 0, 1]]

four    11
one      8
two      9
Name: Utah, dtype: int64

In [46]:
data1.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int64

In [47]:
data1.iloc[2, 3]

11

In [48]:
data1.loc['Colorado', 'two']

5

In [49]:
data1.loc[:'Utah', 'two']

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int64

In [50]:
data1.iloc[:, :3][data.three > 5]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

In [52]:
ser1 = pd.Series(np.arange(3.))
ser1

0    0.0
1    1.0
2    2.0
dtype: float64

In [53]:
ser1[-1]

KeyError: -1

In [55]:
ser2 = pd.Series(np.arange(3.), index=['a', 'b', 'c'])
ser2[-1]

2.0

In [56]:
ser1[:1]

0    0.0
dtype: float64

In [57]:
ser2[:1]

a    0.0
dtype: float64

In [58]:
ser1.iloc[:1]

0    0.0
dtype: float64

In [59]:
ser2.loc[:'a']

a    0.0
dtype: float64

In [60]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'b', 'c', 'd'])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1], index=['a', 'c', 'e', 'f', 'g'])

In [61]:
s1

a    7.3
b   -2.5
c    3.4
d    1.5
dtype: float64

In [62]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [63]:
s1 + s2

a    5.2
b    NaN
c    7.0
d    NaN
e    NaN
f    NaN
g    NaN
dtype: float64

In [66]:
df1 = pd.DataFrame(np.arange(9.).reshape((3,3)), columns=list('bcd'),
               index=['Ohio', 'Texas', 'Colorado'])
df2 = pd.DataFrame(np.arange(12.).reshape((4,3)), columns=list('bde'),
               index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [67]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [68]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [69]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [70]:
df1 = pd.DataFrame({'A': [1, 2]})
df2 = pd.DataFrame({'B': [3, 4]})

In [71]:
df1

A
0  1
1  2

In [72]:
df2

B
0  3
1  4

In [73]:
df1 - df2

A   B
0 NaN NaN
1 NaN NaN

In [74]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)), columns=list('abcd'))
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)), columns=list('abcde'))
df2.loc[1, 'b'] = np.nan

In [75]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [76]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [77]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [78]:
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [84]:
1 / df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [85]:
df1.rdiv(1)

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [86]:
df1.div(1)

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [87]:
df1.reindex(columns=df2.columns, fill_value=0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

In [90]:
arr = np.arange(12.).reshape((3, 4))
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [91]:
arr[0]

array([0., 1., 2., 3.])

In [92]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [93]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)),
                    columns=list('bde'),
                    index=['Utah', 'Ohio', 'Texas', 'Oregon'])
series = frame.iloc[0]
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [94]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [95]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [99]:
series2 = pd.Series(range(3), index=list('bef'))
series2

b    0
e    1
f    2
dtype: int64

In [100]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [101]:
series3 = frame['d']

In [102]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [103]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [104]:
frame.sub(series3, axis='index')

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

In [105]:
frame = pd.DataFrame(np.random.randn(4, 3), columns=list('bde'),
                    index=['Utah', 'Ohio', 'Texas', 'Oregon'])
frame

b         d         e
Utah    0.238496 -0.002889  0.773792
Ohio   -0.813673  1.134909 -0.162736
Texas   0.908037  1.196287  0.909695
Oregon -0.378156  1.641888 -1.649554

In [106]:
np.abs(frame)

b         d         e
Utah    0.238496  0.002889  0.773792
Ohio    0.813673  1.134909  0.162736
Texas   0.908037  1.196287  0.909695
Oregon  0.378156  1.641888  1.649554

In [107]:
f = lambda x: x.max() - x.min()

In [110]:
frame.apply(f)

b    1.721710
d    1.644777
e    2.559250
dtype: float64

In [111]:
frame.apply(f, axis='columns')

Utah      0.776681
Ohio      1.948582
Texas     0.288250
Oregon    3.291442
dtype: float64

In [112]:
def f(x):
    return pd.Series([x.min(), x.max()], index=['min', 'max'])

In [113]:
frame.apply(f)

b         d         e
min -0.813673 -0.002889 -1.649554
max  0.908037  1.641888  0.909695

In [114]:
format = lambda x: '%.2f' % x

In [116]:
frame.applymap(format)

b      d      e
Utah     0.24  -0.00   0.77
Ohio    -0.81   1.13  -0.16
Texas    0.91   1.20   0.91
Oregon  -0.38   1.64  -1.65

In [119]:
frame['d'].map(format)

Utah      -0.00
Ohio       1.13
Texas      1.20
Oregon     1.64
Name: d, dtype: object

In [120]:
obj = pd.Series(range(4), index=['b', 'a', 'd', 'c'])
obj.sort_index()

a    1
b    0
c    3
d    2
dtype: int64

In [ ]:
frame = pd.DataFrame(np.)